# KXTRUMPMENTION-26OCT07: Trump midterm rally, San Antonio TX (Freeman Coliseum), Wed Oct 7 2026.
# Hit counts are real Kalshi settlements from the last four midterm rallies (Durant OK Oct 1, Mobile AL Oct 2,
# Vandalia OH Oct 3, Grand Island NE Oct 5). Words not offered at every rally say so. Nothing else is counted.
EVENT = "KXTRUMPMENTION-26OCT07"
P = EVENT + "-"
DATA = {
  "title": "Trump midterm rally in San Antonio, Texas",
  "speaker": "Donald Trump",
  "event_time_et": "2026-10-07T19:00:00-04:00",
  "event_time_note": "GOP/Trump 47 and the White House schedule: doors 2:30 p.m. CT, program 4:30 p.m. CT, Trump speaks at 6:00 p.m. CT (7:00 p.m. ET), Freeman Coliseum.",
  "context": ("Fifth midterm rally in a week. Ken Paxton (Senate, vs. James Talarico) and Carlos De La Cruz (TX-35) are on the program, so Paxton and Talarico are near-locks. "
              "The stump has been steady: Oil/Gas, Fake News, Transgender, Dividend, Healthcare, Fraud, Save America Act, Barack Hussein Obama, Cheat and Made in America hit 4 of 4. "
              "Deport, Fentanyl, TrumpRx, Trump Account, Ceasefire, Filibuster and Crypto went 0 of 4 even at rallies where border talk was natural. "
              "Texas lifts border, oil and Gulf words a little; a San Antonio crowd could pull a border riff, which is the main risk to the NO leans."),
  "confidence": "Medium. Four same-format rallies this week, all settled.",
  "method": "Presence in the 4 settled midterm rallies (OK, AL, OH, NE), with small Texas adjustments for border, oil and Gulf words.",
  "sources": [
    {"title": "GOP: Midterm Rally in San Antonio (Trump at 6:00 p.m. CT)", "url": "https://events.gop.com/events/midterm-rally-in-san-antonio-texas-president-donald-j-trump"},
    {"title": "San Antonio Express-News: Trump rallies with Paxton, De La Cruz", "url": "https://www.expressnews.com/politics/article/donald-trump-san-antonio-rally-ken-paxton-22464430.php"},
    {"title": "KSAT: Trump to host rally at Freeman Coliseum", "url": "https://www.ksat.com/news/local/2026/10/02/president-trump-to-host-rally-in-san-antonio-on-wednesday/"},
    {"title": "Kalshi settlements: KXTRUMPMENTION-26OCT01 / 02 / 03 / 05", "url": "https://kalshi.com/markets/kxtrumpmention"},
  ],
  "words": {
    P+"PAXT": {"p": 0.98, "reason": "Paxton is on the program and the rally is for him. Near-lock."},
    P+"TALA": {"p": 0.96, "reason": "Talarico is Paxton's opponent; Trump name-checks or nicknames opponents at candidate rallies. Fair."},
    P+"OIL":  {"p": 0.97, "reason": "4 of 4 rallies this week, and Texas is oil country. Fair."},
    P+"FAKE": {"p": 0.96, "reason": "4 of 4 this week. Fair."},
    P+"TRAN": {"p": 0.96, "reason": "4 of 4 this week. Fair."},
    P+"SAVE": {"p": 0.94, "reason": "4 of 4 this week. Fair."},
    P+"FRAU": {"p": 0.95, "reason": "4 of 4 this week. Fair."},
    P+"DIVI": {"p": 0.95, "reason": "4 of 4 this week. Fair."},
    P+"HEAL": {"p": 0.94, "reason": "4 of 4 this week. Fair."},
    P+"CHEA": {"p": 0.92, "reason": "4 of 4 this week. Fair."},
    P+"BARA": {"p": 0.92, "reason": "4 of 4 this week. Fair."},
    P+"AFFO": {"p": 0.86, "reason": "3 of 4 (missed in Durant). Fair."},
    P+"KAMA": {"p": 0.86, "reason": "Offered once this week (NE) and hit. Fair."},
    P+"ICE":  {"p": 0.82, "reason": "3 of 4 this week; a Texas crowd helps. Fair."},
    P+"CHIN": {"p": 0.82, "reason": "3 of 4 this week. Fair."},
    P+"SLEE": {"p": 0.78, "reason": "3 of 4 (missed in Mobile). Fair."},
    P+"MADE": {"p": 0.86, "reason": "4 of 4 this week. Fair to slightly cheap."},
    P+"RUSS": {"p": 0.74, "reason": "3 of 4 (missed in Durant). Fair."},
    P+"BLOC": {"p": 0.72, "reason": "Hit in Grand Island and at Anduril, the two times it was offered this week. Fair."},
    P+"AI":   {"p": 0.60, "reason": "2 of 4 this week (OH, NE yes; OK, AL no). 70¢ looks a bit rich."},
    P+"SUPR": {"p": 0.72, "reason": "3 of 4 (missed in Mobile). Fair."},
    P+"GULF": {"p": 0.70, "reason": "Hit in Mobile, the one rally where it was offered; a Texas Gulf state helps. Fair."},
    P+"ISRA": {"p": 0.50, "reason": "1 of 3 rallies where offered (NE yes; AL, OH no). 64¢ looks rich."},
    P+"HORM": {"p": 0.50, "reason": "2 of 4 this week (OH and AL no; NE yes; OK no). Fair to rich at 60¢."},
    P+"DATA": {"p": 0.45, "fragile": True, "reason": "1 of 4 this week (OH only). Texas data center buildout could pull it in, so the NO is not a lock. 59¢ looks rich."},
    P+"IRAN": {"p": 0.50, "reason": "Contract needs 5+ mentions; 2 of 4 this week. Fair."},
    P+"DRIL": {"p": 0.52, "reason": "1 of 4 this week, the one hit was oil-state Oklahoma. Texas oil helps. Fair."},
    P+"AMER": {"p": 0.32, "reason": "1 of 4 this week (Mobile). Fair."},
    P+"DEPO": {"p": 0.20, "fragile": True, "reason": "0 of 4 this week, even in border-heavy riffs. A San Antonio border segment is the risk. 31¢ looks rich."},
    P+"SANC": {"p": 0.28, "reason": "1 of 4 this week (OH). Fair."},
    P+"FENT": {"p": 0.16, "fragile": True, "reason": "0 of 4 this week. 26¢ looks rich."},
    P+"PALE": {"p": 0.12, "reason": "0 of 1 this week where offered. Fair to rich."},
    P+"TRUMA":{"p": 0.07, "reason": "0 of 4 this week. Fair."},
    P+"TRUM": {"p": 0.05, "reason": "TrumpRx 0 of 4 this week. Fair."},
    P+"CEAS": {"p": 0.04, "reason": "0 of 4 this week. Fair."},
    P+"PEAC": {"p": 0.04, "reason": "Not hit this week. Fair."},
    P+"FILI": {"p": 0.03, "reason": "0 of 4 this week. Fair."},
    P+"CRYP": {"p": 0.02, "reason": "0 of 4 this week. Fair."},
    P+"NQE":  {"p": 0.01, "reason": "Rally is on the White House schedule; cancellation unlikely."},
  },
}
