# KXTRUMPMENTION-26OCT02: Trump midterm rally, Mobile AL (Mitchell Center), Fri Oct 2 2026.
EVENT = "KXTRUMPMENTION-26OCT02"
P = EVENT + "-"
DATA = {
  "title": "Trump midterm rally in Mobile, Alabama",
  "speaker": "Donald Trump",
  "event_time_et": "2026-10-02T19:00:00-04:00",
  "event_time_note": "GOP/Trump 47: program begins 6:00 p.m. Central (7:00 p.m. ET) at USA Mitchell Center, Mobile AL.",
  "context": ("Second midterm rally in two nights (after Durant OK). Expect the same long stump: Fake News, Transgender, "
              "Sleepy Joe, Oil/Gas, Save America Act, Affordability, healthcare/TrumpRx. Alabama is a deep-red room, so "
              "culture-war and election-integrity riffs run hot; foreign-policy blocks (Hormuz, Israel, Russia/Ukraine) are "
              "optional add-ons. 'Space Force' has a Gulf-Coast / military flavor that can land here. Correlated YES staples."),
  "confidence": "Medium. Same rally base rates as Oklahoma; back-to-back schedule makes a shortened speech a real (small) risk.",
  "method": "Presence rates in 23 Jun–Aug 2026 SEL + 4 Sep-2026 speeches, adjusted UP for a full midterm rally.",
  "sources": [
    {"title": "Trump 47 / GOP: Midterm Rally in Mobile, Alabama (Oct 2, 6pm CT)", "url": "https://events.gop.com/events/midterm-rally-in-mobile-alabama-president-trump"},
    {"title": "WEAR: Trump Mitchell Center Mobile Oct 2", "url": "https://weartv.com/news/local/president-trump-coming-to-mobile-on-oct-2-for-rally-at-usas-mitchell-center"},
    {"title": "govinfo CPD Trump remarks corpus", "url": "https://www.govinfo.gov/app/collection/cpd"},
  ],
  "words": {
    P+"TRAN": {"p": 0.92, "reason": "Trail staple; 15/27 official docs. Fair at 90–91¢."},
    P+"FAKE": {"p": 0.92, "reason": "'Fake News' near-automatic at rallies (17/27 corpus). Fair."},
    P+"OIL":  {"p": 0.92, "reason": "Oil/gas in 24/27. Fair at 90–94¢."},
    P+"SLEE": {"p": 0.90, "reason": "'Sleepy Joe' in 17/27; classic rally closer. Fair at 82–91¢."},
    P+"SAVE": {"p": 0.85, "reason": "'Save America Act' is the midterm bill pitch. Fair at 81–91¢."},
    P+"HEAL": {"p": 0.85, "reason": "Healthcare block is live on the trail. Fair at 88–90¢."},
    P+"CHIN": {"p": 0.88, "reason": "China in 20/27. Fair."},
    P+"AFFO": {"p": 0.85, "reason": "Affordability midterm frame. Fair at 76–83¢."},
    P+"DIVI": {"p": 0.80, "reason": "Dividend/stimulus stump promise. Fair."},
    P+"IRAN": {"p": 0.72, "reason": "Iran (5+ times): 19/27 cleared 5+. Fair at 59–65¢."},
    P+"SUPR": {"p": 0.55, "reason": "Supreme Court in 13/27. Fair at 64–75¢ — slight NO lean."},
    P+"BARA": {"p": 0.58, "reason": "'Barack Hussein Obama' in 14/27. Fair."},
    P+"SPAC": {"p": 0.45, "reason": "'Space Force' in 6/27; Gulf military crowd can pull it in. Fair at 55–62¢ — slight NO."},
    P+"HORM": {"p": 0.42, "reason": "Hormuz in 16/27 when Iran is hot; not every rally. Fair at 45–56¢."},
    P+"AMER": {"p": 0.50, "reason": "'America First' in 8/27. Fair."},
    P+"FRAU": {"p": 0.55, "reason": "Fraud talk rises near midterms. Fair."},
    P+"ICE":  {"p": 0.60, "reason": "ICE / border block. Fair."},
    P+"DEPO": {"p": 0.55, "reason": "Deportation language common on trail. Fair at 31–41¢ — slight cheap."},
    P+"FENT": {"p": 0.55, "reason": "Fentanyl tied to border/China. Fair at 28–38¢ — slight cheap."},
    P+"TRUMA": {"p": 0.45, "reason": "'Trump Account' in 8/27. Fair at 34–40¢."},
    P+"AI":   {"p": 0.50, "reason": "AI less forced at an AL midterm rally than at a tech event. Fair at 38–47¢."},
    P+"RUSS": {"p": 0.42, "reason": "Russia/Ukraine optional here. Fair at 40–45¢."},
    P+"TRUM": {"p": 0.42, "reason": "TrumpRX if healthcare block lands. Fair."},
    P+"CHEA": {"p": 0.48, "reason": "Cheat/cheater in 13/27. Fair."},
    P+"SANC": {"p": 0.40, "reason": "Sanctuary in 3/27 official. Fair-to-slight NO at 46–64¢."},
    P+"MADE": {"p": 0.40, "reason": "Made in America in 9/27. Fair at 27–38¢."},
    P+"ISRA": {"p": 0.28, "reason": "Israel in 8/27; foreign-policy optional. Fair at 17–25¢."},
    P+"DATA": {"p": 0.20, "reason": "Data center is a tech-event word. Fair at 14–25¢."},
    P+"FILI": {"p": 0.22, "reason": "Filibuster in 3/27. Fair at 16–21¢."},
    P+"DRIL": {"p": 0.28, "reason": "'Drill baby drill' rare in corpus (2/27) but energy riffs help. Fair at 10–18¢ — slight cheap."},
    P+"CEAS": {"p": 0.15, "reason": "Ceasefire uncommon at domestic rallies. Fair at 8–11¢."},
    P+"CRYP": {"p": 0.06, "reason": "Crypto rare on the trail. Fair at 1–2¢."},
    P+"NQE":  {"p": 0.02, "reason": "Publicly scheduled; cancellation unlikely."},
  },
}
