# KXTRUMPMENTION-26OCT09: Trump midterm rally, Syracuse NY (Oncenter), Fri Oct 9 2026. Remarks 7:00 p.m. ET.
EVENT = "KXTRUMPMENTION-26OCT09"
P = EVENT + "-"
DATA = {
  "title": "Trump midterm rally in Syracuse, New York",
  "speaker": "Donald Trump",
  "event_time_et": "2026-10-09T19:00:00-04:00",
  "event_time_note": "GOP: doors 3:00 p.m. ET, program 5:30 p.m. ET, Trump remarks 7:00 p.m. ET at the Oncenter, 800 S. State St., Syracuse NY.",
  "context": ("Trump is in Syracuse to boost Bruce Blakeman, the GOP nominee running against Gov. Kathy Hochul, so Hochul is the obvious foil. "
              "New York hooks make NYC Mayor Zohran Mamdani and sanctuary-city talk more natural than on the Ohio and Oklahoma stops. "
              "Micron's planned chip megafab in nearby Clay, NY is a local economic brag he has reasons to cite. "
              "The rest of the board follows the usual long stump: Fake News, Transgender, oil and gas, affordability, healthcare, Save America Act."),
  "confidence": "Medium. Same rally base rates as the October stops, adjusted for New York hooks.",
  "method": "Presence rates from the Jun to Oct 2026 rally corpus used for the Ohio, Oklahoma and Alabama boards, adjusted for the New York setting.",
  "sources": [
    {"title": "GOP: Midterm Rally in Syracuse, NY (remarks 7:00 p.m. ET)", "url": "https://events.gop.com/events/midterm-rally-in-syracuse-ny-president-donald-j-trump"},
    {"title": "Syracuse.com: Trump rally will be at the Oncenter", "url": "https://www.syracuse.com/politics/cny/2026/10/trumps-campaign-rally-in-syracuse-will-be-at-the-oncenter.html"},
    {"title": "CNY Central: Trump in Syracuse to endorse Blakeman", "url": "https://cnycentral.com/news/local/president-trump-in-syracuse-on-friday-how-law-enforcement-is-preparing"},
  ],
  "words": {
    P+"TRAN": {"p": 0.95, "reason": "Trail staple. Fair, slightly rich."},
    P+"OIL":  {"p": 0.93, "reason": "Oil and gas in most rallies. Fair."},
    P+"FAKE": {"p": 0.95, "reason": "'Fake News' is near-automatic at rallies. Fair."},
    P+"DIVI": {"p": 0.90, "reason": "Dividend or stimulus promise is a current stump line. Fair."},
    P+"HOCH": {"p": 0.96, "reason": "The rally is about beating Hochul. Fair."},
    P+"HEAL": {"p": 0.90, "reason": "Healthcare block is live on the trail. Fair."},
    P+"SAVE": {"p": 0.88, "reason": "Save America Act is a midterm pitch. Fair."},
    P+"SANC": {"p": 0.90, "reason": "Sanctuary-state talk is natural in New York. Fair."},
    P+"MADE": {"p": 0.80, "reason": "Made in America fits a chip-plant brag. Fair, slightly rich."},
    P+"AFFO": {"p": 0.88, "reason": "Affordability midterm frame. Fair."},
    P+"KAMA": {"p": 0.82, "reason": "Kamala is a regular foil. Fair."},
    P+"ICE":  {"p": 0.78, "reason": "ICE comes with the sanctuary block. Fair."},
    P+"ZOHR": {"p": 0.86, "reason": "A New York rally makes Mamdani one of the most natural foils on the board, and Trump names him often. Slight YES lean."},
    P+"MICR": {"p": 0.78, "reason": "Micron's megafab is next door in Clay; a local jobs brag is likely but not certain. Fair."},
    P+"AI":   {"p": 0.72, "reason": "AI rides along with the chip-plant story. Fair."},
    P+"CHIN": {"p": 0.70, "reason": "China in most rallies. Fair."},
    P+"CHEA": {"p": 0.62, "reason": "Cheat or cheating appears in about half of rallies. Fair."},
    P+"SLEE": {"p": 0.65, "reason": "'Sleepy Joe' is a classic but less frequent lately. Fair."},
    P+"BARA": {"p": 0.60, "reason": "'Barack Hussein Obama' in a bit over half. Fair."},
    P+"ISRA": {"p": 0.52, "reason": "Israel is a coin flip at a domestic rally. Fair."},
    P+"HORM": {"p": 0.50, "reason": "Hormuz shows up when Iran is hot. Fair."},
    P+"TRUMA": {"p": 0.48, "reason": "Trump Account is optional. Fair."},
    P+"IRAN": {"p": 0.50, "reason": "Five or more Iran mentions is a high bar. Fair."},
    P+"FRAU": {"p": 0.50, "reason": "Three or more fraud mentions is a coin flip. Fair."},
    P+"BLOC": {"p": 0.45, "reason": "Blockade depends on the Iran block. Fair."},
    P+"SUPR": {"p": 0.45, "reason": "Supreme Court is optional. Fair."},
    P+"RUSS": {"p": 0.43, "reason": "Russia or Ukraine is optional. Fair."},
    P+"GULF": {"p": 0.42, "reason": "Gulf of America is an occasional riff. Fair."},
    P+"PALE": {"p": 0.36, "reason": "Palestine is uncommon at domestic rallies. Fair."},
    P+"DEPO": {"p": 0.32, "reason": "Deportation language is optional. Fair."},
    P+"DATA": {"p": 0.28, "reason": "Data center is a tech-event word. Fair."},
    P+"AMER": {"p": 0.18, "reason": "'America First' as a phrase is uncommon lately. Fair."},
    P+"FENT": {"p": 0.12, "reason": "Fentanyl has faded from the stump. Fair."},
    P+"DRIL": {"p": 0.08, "reason": "'Drill baby drill' is rare now. Fair."},
    P+"PEAC": {"p": 0.04, "reason": "That exact phrase is rare. Fair."},
    P+"CEAS": {"p": 0.04, "reason": "Ceasefire is uncommon at domestic rallies. Fair."},
    P+"TRUM": {"p": 0.03, "reason": "TrumpRx rarely named at rallies now. Fair."},
    P+"CRYP": {"p": 0.02, "reason": "Crypto is rare on the trail. Fair."},
    P+"NQE":  {"p": 0.01, "reason": "Publicly scheduled; cancellation unlikely."},
  },
}
